<a href="https://colab.research.google.com/github/lmassaron/ml4dummies_3ed/blob/main/ML4D3E_07_demystifying_the_math_behind_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
myvect = np.array([1, 2, 3, 4])
myvect

array([1, 2, 3, 4])

In [3]:
myvect = np.arange(1, 10, 2)
myvect

array([1, 3, 5, 7, 9])

In [4]:
myvect = np.array([1, 2, 3, 4], dtype=np.int16)
myvect

array([1, 2, 3, 4], dtype=int16)

In [5]:
myvect = np.ones(4, dtype=np.int16)
myvect

array([1, 1, 1, 1], dtype=int16)

In [6]:
myvect = np.array([1, 2, 3, 4])

In [7]:
myvect + 1

array([2, 3, 4, 5])

In [8]:
myvect - 1

array([0, 1, 2, 3])

In [9]:
myvect = np.array([1, 2, 3, 4])
2 ** myvect

array([ 2,  4,  8, 16])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [11]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


In [12]:
myvect = np.array([1, 2, 3, 4])
myvect.dot(myvect)

np.int64(30)

In [13]:
a = np.array([[1, 1], [1, 0]])
b = np.array([[1, 0], [0, 1]])
c = a - b

print(c)

[[ 0  1]
 [ 1 -1]]


In [14]:
print(c * -2)

[[ 0 -2]
 [-2  2]]


In [15]:
X = np.array([[4, 5], [2, 4], [3, 3]])
b = [3, -2]
print(X @ b)

[ 2 -2  3]


In [16]:
B = np.array([[3, -2], [-2, 5]])
print(X @ B)

[[ 2 17]
 [-2 16]
 [ 3  9]]


In [17]:
a = np.array([[1, 2, 3], [2, 3, 5], [7, 11, 13]])
print(a.transpose())

[[ 1  2  7]
 [ 2  3 11]
 [ 3  5 13]]


In [18]:
print(np.linalg.inv(a))

[[-3.2  1.4  0.2]
 [ 1.8 -1.6  0.2]
 [ 0.2  0.6 -0.2]]


In [19]:
y = np.array([44, 21, 37])
print(y)
print(y.shape)

[44 21 37]
(3,)


In [20]:
X = np.array([[1.1, 1, 545, 1],[4.6, 0, 345, 2],
              [7.2, 1, 754, 3]])
print(X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [21]:
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2,
              7.2, 1, 754, 3]).reshape(3, 4)
X

array([[  1.1,   1. , 545. ,   1. ],
       [  4.6,   0. , 345. ,   2. ],
       [  7.2,   1. , 754. ,   3. ]])